### ISSUE TITLE
[BUG] Editing caption of message with multiple image adds caption to last image instead of first

### ISSUE THREAD

**Issue by LeonTheOriginal** [morethanwords/tweb#120] opened 2022-04-17 22:25 UTC
**Describe the bug**
Trying to edit the caption of a message with two or more images (or videos), Telegram Web K edits the caption of (or adds one to) the last image. This also causes the caption in the chat to disappear as the initial caption is still there.

**To Reproduce**
1. Create a message with 2 or more images and add caption text (e.g. Text 1).
2. Send message.
3. Edit message (notice that edit box is empty) and add caption (e.g. Text 2).
4. Result: Instead of editing "Text 1", "Text 2" was added to the last image. Image 1 still has "Text 1" as caption. Caption text attached to the message in the chat disappered as now there are different captions on different images. (This is an expected behavior.)

**Expected behavior**
By default, always the caption text of the first image should be ediited and/or it should be possible to edit the caption text of each individual image.

**Smartphone**
 Tested with Opera 68 on Android 7.

**Additional context**
Handling of messages with multiple media seems to be very limited in Telegram Web K. Ordering or consecutive adding of single images as well as adding captions to individual items is not possible at the moment. See also my additional feature requests in bug #119, which I just created.

**Comment by fromaline** [comment] 2022-09-30 16:55
I can't reproduce the bug now on a phone, because there is no "Edit" option in the context menu at all. Is it still valid for you?

![photo_2022-09-30_20-52-45](https://user-images.githubusercontent.com/55146773/193319728-3660e98c-6627-49cf-a952-373bd9817085.jpg)

**Comment by morethanwords** [comment] 2023-11-24 19:07
Thank you for the report! Fixed in beta.

**Closed by morethanwords** 2023-11-24 19:07 UTC
Labels: bug
