### ISSUE TITLE
[BUG] some files not found

### ISSUE THREAD

**Issue by ruslan-gennadievich** [morethanwords/tweb#27] opened 2021-05-27 16:17 UTC
Hello

Just run npm i && npm start:

```
ERROR in ./src/components/sidebarRight/tabs/gifs.ts
Module not found: Error: Can't resolve '../../../lib/appManagers/appInlineBotsManager' in '/home/ruslan/Документы/tweb/src/components/sidebarRight/tabs'
 @ ./src/components/sidebarRight/tabs/gifs.ts 20:0-81 95:37-57
 @ ./src/components/emoticonsDropdown/index.ts
 @ ./src/components/chat/input.ts
 @ ./src/components/chat/chat.ts
 @ ./src/lib/appManagers/appImManager.ts
 @ ./src/lib/appManagers/appDialogsManager.ts
 @ ./src/pages/pageIm.ts
 @ ./src/index.ts

ERROR in ./src/components/chat/autocompleteHelper.ts
Module not found: Error: Can't resolve '../../helpers/dom/attachlistNavigation' in '/home/ruslan/Документы/tweb/src/components/chat'
 @ ./src/components/chat/autocompleteHelper.ts 6:0-74 21:44-64
 @ ./src/components/chat/stickersHelper.ts
 @ ./src/components/chat/input.ts
 @ ./src/components/chat/chat.ts
 @ ./src/lib/appManagers/appImManager.ts
 @ ./src/lib/appManagers/appDialogsManager.ts
 @ ./src/pages/pageIm.ts
 @ ./src/index.ts

ERROR in ./src/lib/appManagers/appImManager.ts
Module not found: Error: Can't resolve './appInlineBotsManager' in '/home/ruslan/Документы/tweb/src/lib/appManagers'
 @ ./src/lib/appManagers/appImManager.ts 28:0-58 620:69-89
 @ ./src/lib/appManagers/appDialogsManager.ts
 @ ./src/pages/pageIm.ts
 @ ./src/index.ts

ERROR in /home/ruslan/Документы/tweb/src/components/chat/autocompleteHelper.ts
./src/components/chat/autocompleteHelper.ts 7:33-73
[tsl] ERROR in /home/ruslan/Документы/tweb/src/components/chat/autocompleteHelper.ts(7,34)
      TS2307: Cannot find module '../../helpers/dom/attachlistNavigation' or its corresponding type declarations.

ERROR in /home/ruslan/Документы/tweb/src/components/chat/bubbles.ts
./src/components/chat/bubbles.ts 11:42-86
[tsl] ERROR in /home/ruslan/Документы/tweb/src/components/chat/bubbles.ts(11,43)
      TS2307: Cannot find module '../../lib/appManagers/appInlineBotsManager' or its corresponding type declarations.

ERROR in /home/ruslan/Документы/tweb/src/components/chat/chat.ts

```

**Comment by morethanwords** [comment] 2021-05-28 13:11
Please check your npm and node versions (I'm using 6.14.8 and 14.15.1), I can't reproduce the bug.

**Comment by morethanwords** [comment] 2021-06-03 13:20
Thank you for investigating and fixing the bug! I've merged pull request, so I think it's fixed now.

**Closed by morethanwords** 2021-06-03 13:20 UTC
Labels: bug
