### ISSUE TITLE
[BUG] Image file previews broken when forwarded to Saved Messages

### ISSUE THREAD

**Issue by erayrafet** [morethanwords/tweb#126] opened 2022-05-08 15:52 UTC
**Describe the bug**
Image file previews do break once forwarded to the Saved Messages section. They get fixed after reloading.

**To Reproduce**
1. Go to '[https://t.me/dailywalls/9503](https://t.me/dailywalls/9503)'
2. Click on 'the forward icon'
3. Select 'Saved Messages'

**Expected behavior**
The image file preview to be displayed.

**Screenshots**
[Screen Recording](https://photos.app.goo.gl/JaqF32XEmB8FkcVj7)

**Desktop (please complete the following information):**
 - OS: ChromeOS Flex 102 Beta
 - Browser: Chrome
 - Version: 102

[web.telegram.org-1652025105527.log](https://github.com/morethanwords/tweb/files/8647310/web.telegram.org-1652025105527.log)

**Comment by fromaline** [comment] 2022-09-30 16:28
I can't reproduce this bug at all in the current version of Telegram Web. It seems like it was fixed.

**Comment by erayrafet** [comment] 2022-09-30 16:37
> I can't reproduce this bug at all in the current version of Telegram Web. It seems like it was fixed.

I can reproduce it still on ChromeOS Flex 105. 
![image](https://user-images.githubusercontent.com/34194191/193316884-c74cd20f-57fe-4ee5-bfd3-386dab6cba0a.png)
The thumbnail file looks broken.

**Comment by fromaline** [comment] 2022-09-30 17:01
Oh, you submitted the bug with ChromeOS in the OS filed. It's my fault, I tested it on Linux.

**Comment by erayrafet** [comment] 2022-09-30 17:18
@fromaline You can change your browser user-agent to ChromeOS and test that way.

**Comment by morethanwords** [comment] 2022-11-19 13:03
Thank you for the report! Fixed in 1.6.2 (261).

**Closed by morethanwords** 2022-11-19 13:03 UTC
Labels: bug
